services:
  discovery-service:
    build: discovery-service
    container_name: amani-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4

  config-service:
    build: config-service
    container_name: amani-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://amani-discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 15s
      retries: 5
      start_period: 30s
    depends_on:
      discovery-service:
        condition: service_healthy

  customer-service:
    build: customer-service
    container_name: amani-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://amani-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://amani-config-service:9999
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 20s
      retries: 7
      start_period: 35s
    depends_on:
      config-service:
        condition: service_healthy

  account-service:
    build: account-service
    container_name: amani-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://amani-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://amani-config-service:9999
    depends_on:
      customer-service:
        condition: service_healthy

  gateway-service:
    build: gateway-service
    container_name: amani-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://amani-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://amani-config-service:9999
    depends_on:
      config-service:
        condition: service_healthy

  front-send-angular:
    build: angular-frontend
    container_name: front-end
    ports:
      - '82:80'
    expose:
      - '82'
